// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `DistributedSharedLock.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.yonyou.mcloud.service.lock;

public abstract class Callback_DistributedSharedLock_tryLockInTime
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackBoolUE
{
    public final void __completed(Ice.AsyncResult __result)
    {
        DistributedSharedLockPrxHelper.__tryLockInTime_completed(this, __result);
    }
}
