// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `DistributedSharedLock.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.yonyou.mcloud.service.lock;

public final class DistributedSharedLockHolder extends Ice.ObjectHolderBase<DistributedSharedLock>
{
    public
    DistributedSharedLockHolder()
    {
    }

    public
    DistributedSharedLockHolder(DistributedSharedLock value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof DistributedSharedLock)
        {
            value = (DistributedSharedLock)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _DistributedSharedLockDisp.ice_staticId();
    }
}
