// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `DistributedSharedLock.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.yonyou.mcloud.service.lock;

public class LockException extends Ice.UserException
{
    public LockException()
    {
        resion = "";
    }

    public LockException(Throwable __cause)
    {
        super(__cause);
        resion = "";
    }

    public LockException(String resion)
    {
        this.resion = resion;
    }

    public LockException(String resion, Throwable __cause)
    {
        super(__cause);
        this.resion = resion;
    }

    public String
    ice_name()
    {
        return "lock::LockException";
    }

    public String resion;

    protected void
    __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice("::lock::LockException", -1, true);
        __os.writeString(resion);
        __os.endWriteSlice();
    }

    protected void
    __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        resion = __is.readString();
        __is.endReadSlice();
    }

    public static final long serialVersionUID = 1911191223L;
}
