// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `IdGenerator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.yonyou.mcloud.service.common;

public final class IdGeneratorHolder extends Ice.ObjectHolderBase<IdGenerator>
{
    public
    IdGeneratorHolder()
    {
    }

    public
    IdGeneratorHolder(IdGenerator value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof IdGenerator)
        {
            value = (IdGenerator)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _IdGeneratorDisp.ice_staticId();
    }
}
