// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `CacheService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.yonyou.mcloud.cache;

public class CacheException extends Ice.UserException
{
    public CacheException()
    {
        msg = "";
    }

    public CacheException(Throwable __cause)
    {
        super(__cause);
        msg = "";
    }

    public CacheException(String msg)
    {
        this.msg = msg;
    }

    public CacheException(String msg, Throwable __cause)
    {
        super(__cause);
        this.msg = msg;
    }

    public String
    ice_name()
    {
        return "cache::CacheException";
    }

    public String msg;

    protected void
    __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice("::cache::CacheException", -1, true);
        __os.writeString(msg);
        __os.endWriteSlice();
    }

    protected void
    __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        msg = __is.readString();
        __is.endReadSlice();
    }

    public static final long serialVersionUID = 755405474L;
}
