// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `CacheService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.yonyou.mcloud.cache;

public interface CacheService extends Ice.Object,
                                      _CacheServiceOperations, _CacheServiceOperationsNC
{
    public static final String ice_staticId = "::cache::CacheService";

    public static final long serialVersionUID = 1650239424L;
}
