// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `CacheService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.yonyou.mcloud.cache;

public interface CacheServicePrx extends Ice.ObjectPrx
{
    public java.io.Serializable get(String key)
        throws CacheException;

    public java.io.Serializable get(String key, java.util.Map<String, String> __ctx)
        throws CacheException;

    public Ice.AsyncResult begin_get(String key);

    public Ice.AsyncResult begin_get(String key, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_get(String key, Ice.Callback __cb);

    public Ice.AsyncResult begin_get(String key, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_get(String key, Callback_CacheService_get __cb);

    public Ice.AsyncResult begin_get(String key, java.util.Map<String, String> __ctx, Callback_CacheService_get __cb);

    public Ice.AsyncResult begin_get(String key,
                                     IceInternal.Functional_GenericCallback1<java.io.Serializable> __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_get(String key,
                                     IceInternal.Functional_GenericCallback1<java.io.Serializable> __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                     IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_get(String key,
                                     java.util.Map<String, String> __ctx,
                                     IceInternal.Functional_GenericCallback1<java.io.Serializable> __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_get(String key,
                                     java.util.Map<String, String> __ctx,
                                     IceInternal.Functional_GenericCallback1<java.io.Serializable> __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                     IceInternal.Functional_BoolCallback __sentCb);

    public java.io.Serializable end_get(Ice.AsyncResult __result)
        throws CacheException;

    public boolean add(String key, java.io.Serializable value, int expire)
        throws CacheException;

    public boolean add(String key, java.io.Serializable value, int expire, java.util.Map<String, String> __ctx)
        throws CacheException;

    public Ice.AsyncResult begin_add(String key, java.io.Serializable value, int expire);

    public Ice.AsyncResult begin_add(String key, java.io.Serializable value, int expire, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_add(String key, java.io.Serializable value, int expire, Ice.Callback __cb);

    public Ice.AsyncResult begin_add(String key, java.io.Serializable value, int expire, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_add(String key, java.io.Serializable value, int expire, Callback_CacheService_add __cb);

    public Ice.AsyncResult begin_add(String key, java.io.Serializable value, int expire, java.util.Map<String, String> __ctx, Callback_CacheService_add __cb);

    public Ice.AsyncResult begin_add(String key,
                                     java.io.Serializable value,
                                     int expire,
                                     IceInternal.Functional_BoolCallback __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_add(String key,
                                     java.io.Serializable value,
                                     int expire,
                                     IceInternal.Functional_BoolCallback __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                     IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_add(String key,
                                     java.io.Serializable value,
                                     int expire,
                                     java.util.Map<String, String> __ctx,
                                     IceInternal.Functional_BoolCallback __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_add(String key,
                                     java.io.Serializable value,
                                     int expire,
                                     java.util.Map<String, String> __ctx,
                                     IceInternal.Functional_BoolCallback __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                     IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_add(Ice.AsyncResult __result)
        throws CacheException;

    public boolean set(String key, java.io.Serializable value, int expire)
        throws CacheException;

    public boolean set(String key, java.io.Serializable value, int expire, java.util.Map<String, String> __ctx)
        throws CacheException;

    public Ice.AsyncResult begin_set(String key, java.io.Serializable value, int expire);

    public Ice.AsyncResult begin_set(String key, java.io.Serializable value, int expire, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_set(String key, java.io.Serializable value, int expire, Ice.Callback __cb);

    public Ice.AsyncResult begin_set(String key, java.io.Serializable value, int expire, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_set(String key, java.io.Serializable value, int expire, Callback_CacheService_set __cb);

    public Ice.AsyncResult begin_set(String key, java.io.Serializable value, int expire, java.util.Map<String, String> __ctx, Callback_CacheService_set __cb);

    public Ice.AsyncResult begin_set(String key,
                                     java.io.Serializable value,
                                     int expire,
                                     IceInternal.Functional_BoolCallback __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_set(String key,
                                     java.io.Serializable value,
                                     int expire,
                                     IceInternal.Functional_BoolCallback __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                     IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_set(String key,
                                     java.io.Serializable value,
                                     int expire,
                                     java.util.Map<String, String> __ctx,
                                     IceInternal.Functional_BoolCallback __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_set(String key,
                                     java.io.Serializable value,
                                     int expire,
                                     java.util.Map<String, String> __ctx,
                                     IceInternal.Functional_BoolCallback __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                     IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_set(Ice.AsyncResult __result)
        throws CacheException;

    public boolean evict(String key)
        throws CacheException;

    public boolean evict(String key, java.util.Map<String, String> __ctx)
        throws CacheException;

    public Ice.AsyncResult begin_evict(String key);

    public Ice.AsyncResult begin_evict(String key, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_evict(String key, Ice.Callback __cb);

    public Ice.AsyncResult begin_evict(String key, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_evict(String key, Callback_CacheService_evict __cb);

    public Ice.AsyncResult begin_evict(String key, java.util.Map<String, String> __ctx, Callback_CacheService_evict __cb);

    public Ice.AsyncResult begin_evict(String key,
                                       IceInternal.Functional_BoolCallback __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_evict(String key,
                                       IceInternal.Functional_BoolCallback __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_evict(String key,
                                       java.util.Map<String, String> __ctx,
                                       IceInternal.Functional_BoolCallback __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_evict(String key,
                                       java.util.Map<String, String> __ctx,
                                       IceInternal.Functional_BoolCallback __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                       IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_evict(Ice.AsyncResult __result)
        throws CacheException;
}
