// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `CacheService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.yonyou.mcloud.cache;

public abstract class Callback_CacheService_get
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1UE<java.io.Serializable>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        CacheServicePrxHelper.__get_completed(this, __result);
    }
}
