// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `CacheService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.yonyou.mcloud.cache;

public final class SerializableJavaObjHelper
{
    public static void
    write(IceInternal.BasicStream __os, java.io.Serializable __v)
    {
        __os.writeSerializable(__v);
    }

    public static java.io.Serializable
    read(IceInternal.BasicStream __is)
    {
        java.io.Serializable __v;
        __v = (java.io.Serializable)__is.readSerializable();
        return __v;
    }
}
