// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `IdGenerator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.yonyou.mcloud.idgenerator;

public interface IdGeneratorPrx extends Ice.ObjectPrx
{
    public String nextId();

    public String nextId(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_nextId();

    public Ice.AsyncResult begin_nextId(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_nextId(Ice.Callback __cb);

    public Ice.AsyncResult begin_nextId(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_nextId(Callback_IdGenerator_nextId __cb);

    public Ice.AsyncResult begin_nextId(java.util.Map<String, String> __ctx, Callback_IdGenerator_nextId __cb);

    public Ice.AsyncResult begin_nextId(IceInternal.Functional_GenericCallback1<String> __responseCb,
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_nextId(IceInternal.Functional_GenericCallback1<String> __responseCb,
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_nextId(java.util.Map<String, String> __ctx,
                                        IceInternal.Functional_GenericCallback1<String> __responseCb,
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_nextId(java.util.Map<String, String> __ctx,
                                        IceInternal.Functional_GenericCallback1<String> __responseCb,
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                        IceInternal.Functional_BoolCallback __sentCb);

    public String end_nextId(Ice.AsyncResult __result);
}
